name: nutrical
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  bloc: ^9.0.0
  cloud_firestore: ^5.6.6
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  flow_builder: ^0.1.0
  provider: ^6.1.4
  formz: ^0.8.0
  flutter_gemini: ^3.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
