// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7btDc2CSy3XW93BPablW6qLENvNBJWF4',
    appId: '1:56298213998:web:364a9c984f45092e568c7f',
    messagingSenderId: '56298213998',
    projectId: 'nutrical-1a61d',
    authDomain: 'nutrical-1a61d.firebaseapp.com',
    storageBucket: 'nutrical-1a61d.firebasestorage.app',
    measurementId: 'G-P2EYG4H26S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyj5cdV7I8-p3bmXubAx2iN5YXxHYwazQ',
    appId: '1:56298213998:android:1324d1592b6dfd30568c7f',
    messagingSenderId: '56298213998',
    projectId: 'nutrical-1a61d',
    storageBucket: 'nutrical-1a61d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxcfR8qnrjBCLX2FE57f-Z8STj9UWOemY',
    appId: '1:56298213998:ios:371eab22db35b0b3568c7f',
    messagingSenderId: '56298213998',
    projectId: 'nutrical-1a61d',
    storageBucket: 'nutrical-1a61d.firebasestorage.app',
    iosBundleId: 'com.example.nutrical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxcfR8qnrjBCLX2FE57f-Z8STj9UWOemY',
    appId: '1:56298213998:ios:371eab22db35b0b3568c7f',
    messagingSenderId: '56298213998',
    projectId: 'nutrical-1a61d',
    storageBucket: 'nutrical-1a61d.firebasestorage.app',
    iosBundleId: 'com.example.nutrical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7btDc2CSy3XW93BPablW6qLENvNBJWF4',
    appId: '1:56298213998:web:b8e1f908afe575c5568c7f',
    messagingSenderId: '56298213998',
    projectId: 'nutrical-1a61d',
    authDomain: 'nutrical-1a61d.firebaseapp.com',
    storageBucket: 'nutrical-1a61d.firebasestorage.app',
    measurementId: 'G-13WG5H3NV3',
  );
}
